### ISSUE TITLE
individual town hall and mage guild screens

### ISSUE THREAD

**Issue by swats-the-floran** [vcmi-mods/fairy-town#13]
to make town more unique.

**Comment by Fabrice-TIERCELIN** [comment]
Hi,

There is no valid reason to do so because:

- It's not the case for the original towns
- It's not the case for the modded towns

Only Greenhouse does that because Greenhouse voluntary follows no rules

But I can do that only for you if you want (but I won't ensure the maintenance)

**Comment by Fabrice-TIERCELIN** [comment]
We have done it only for _Ruins_ and _[Greenhouse](https://github.com/vcmi-mods/greenhouse-town/pull/4)_ because it suits the town style. @misiokles, I suggest to close this query.
