### ISSUE TITLE
Update to 2.70

### ISSUE THREAD

**Issue by by003** [vcmi-mods/fairy-town#29]
[fairy-town-vcmi-1.6.zip](https://github.com/user-attachments/files/18237050/fairy-town-vcmi-1.6.zip)

@misiokles please check and test it. 
New fairy mod has a range of changes.
The more beautiful town screen,
Tarot card divination,
New knowledge tree and some decorations.

**Comment by misiokles** [comment]
I will return home on Thursday. I'll ask some other people to test quicker. Thanks!!

**Comment by by003** [comment]
Please add these from town.json
"hallSlots" : [
				[
					[ "villageHall", "townHall", "cityHall", "capitol" ],
					[ "fort", "citadel", "castle" ],
					[ "tavern" ],
					[ "blacksmith" ]
				],
				[
					[ "marketplace", "resourceSilo" ],
					[ "mageGuild1", "mageGuild2", "mageGuild3", "mageGuild4", "mageGuild5" ],
					**[ "special2","special3","special4" ],**[ "dock" ]
				],
				[ 
					[ "special1" ],
					[ "horde2", "horde2Upgr" ],
			    	[ "horde1", "horde1Upgr" ]
				],
				[
					[ "dwellingLvl1", "dwellingUpLvl1" ],
					[ "dwellingLvl2", "dwellingUpLvl2" ],
					[ "dwellingLvl3", "dwellingUpLvl3" ],
					[ "dwellingLvl4", "dwellingUpLvl4" ]
				],
				[
					[ "dwellingLvl5", "dwellingUpLvl5" ],
					[ "dwellingLvl6", "dwellingUpLvl6" ],
					[ "dwellingLvl7", "dwellingUpLvl7" ]
				]
			]

In lines 1161 
then change:
"hallBackground" : "TPTHBKFR",
to
"hallBackground" : "TPTHBKDG".

change music to "musicTheme" : ["music/factions/fairyTown"],

**Comment by by003** [comment]
> 我周四就回家了。我会叫其他人快点测试。谢谢！！

No worries, wish you merry Christmas.

**Comment by MyroSlave** [comment]
@by003 I've just tested your patch, I see 2 problems for now:
1. Some heroes are missing (the fix is very easy)
2. Starting a map with Fairy town mod enabled (it doesn't even have to be a starting town) crashes the game (no idea why)
[VCMI_Client_log.txt](https://github.com/user-attachments/files/18242052/VCMI_Client_log.txt)

**Comment by by003** [comment]
You need to install hota first

**Comment by MyroSlave** [comment]
@by003 I know, I had it installed, something else is causing the crash

**Comment by by003** [comment]
I think you have downloaded the old pack.
Please download again. Actually I have already edited.
Now I reupload it.
[fairy-town-vcmi-1.6.zip](https://github.com/user-attachments/files/18253406/fairy-town-vcmi-1.6.zip)

**Comment by misiokles** [comment]
I guess, teh problem was in other place - in translation files. I main mod headers of lvl1 creatures have changed - from ftFairy1/ftFairy2 to ftFae1/ftFae2. But translation files hadn't been updated.
For now, mod seems to be working.
