### ISSUE TITLE
New update for seige and new animations

### ISSUE THREAD

**Issue by by003** [vcmi-mods/fairy-town#9]
@misiokles please help me to update new works here.
[fairyUp.zip](https://github.com/vcmi-mods/fairy-town/files/13984182/fairyUp.zip)

the new updates include:
1. Arrow tower in seige screen and new animation of sibyls
2. Spell effect for rose bolt. Everyone will be attacked once if enchanted with garland.
3. New commander's port and animation, for only WOG mod users. Please change the name of small portrait.

And then update the coordinates in seige town creatures.
"towers" :
				{
					"bottom" :
					{
						"battlement" : { "x" : 602, "y" : 500 },
						**"creature" : { "x" : 400, "y" : 302},**
						"tower" : { "x" : 602, "y" : 500 }
					},
					"keep" :
					{
						"battlement" : { "x" : 720, "y" : 158 },
						"creature" : { "x" : 526, "y" : -29 },
						"tower" : { "x" : 720, "y" : 158 }
					},
					"top" :
					{
						"battlement" : { "x" : 557, "y" : 24 },
						**"creature" : { "x" : 348, "y" : -181 },**
						"tower" : { "x" : 569, "y" : 35 }
					}
				},

**Comment by by003** [comment]
By the way, please update new icons for 1.4.3.
some bonus icons:
1. Damage reduction (type all) and fireshield:
![image](https://github.com/vcmi-mods/fairy-town/assets/127420617/7dcd8d6a-6622-439f-baac-ead2b48e8d8e)
2. 1.4.3 HotA abilities:
![image](https://github.com/vcmi-mods/fairy-town/assets/127420617/ed9ff4f6-c223-4894-ab25-483f5eec5dec)
3. immunity of raised spells (for ring of oblivion)
![image](https://github.com/vcmi-mods/fairy-town/assets/127420617/c403ffdd-03ad-4359-a7fd-bbfec1b3c24d)

[newBonusIcons.zip](https://github.com/vcmi-mods/fairy-town/files/13984265/newBonusIcons.zip)

@misiokles thanks for that

**Comment by misiokles** [comment]
Updated fairy-town. 
But I don't know how to add new icons and don't have access to main vcmi repo and vcmi-extras repo. It's better t summon @dydzio0614 for that.
